sonar.projectKey=PAI-Plataform-Game
sonar.sources=src
sonar.host.url=http://localhost:9000
sonar.login=sqp_4c073d469edcc6a36c6a381a9f01b86f0a90469d
# Para que no analice carpetas de librerías
sonar.exclusions=node_modules/**
sonar.eslint.reportPaths=eslint-report.json